name: Add Changes Requested Label

on:
  pull_request_review:
    types: [changes_requested]


jobs:
  add_changes_requested_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if changes were requested by maintainer or collaborator
        id: check_changes_requested
        uses: actions/github-script@v6
        with:
          script: |
            github.actions.getOctokit().rest.repos.getCollaborator({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.payload.review.user.login
            }).then(response => {
              if (response.status === 204) {
                setContext('isCollaborator', true);
              }
            }).catch(error => {
              setContext('isCollaborator', false);
            });

      - name: Set label based on review
        id: set_label
        run: |
          if [ ${{ steps.check_changes_requested.outputs.isCollaborator }} == "true" ]; then
            echo "Changes requested by maintainer or collaborator, adding label..."
            echo "::set-output name=label::changes requested"
          else
            echo "No changes requested by maintainer or collaborator, no action needed."
            echo "::set-output name=label::no_changes_requested"
          fi

      - name: Add label if changes requested
        if: steps.set_label.outputs.label == 'changes requested'
        uses: actions/github-script@v6
        with:
          script: |
            github.actions.getOctokit().issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['changes requested']
            });
