name: Label Reworks

on:
  pull_request_review:
    types:
      - submitted

jobs:
  label_reworks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Label Reworks
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { payload, github } = context;

            // Check if the review was a request for changes
            if (payload.review.state === 'changes_requested') {
              const prNumber = payload.pull_request.number;

              // Add the "rework" label to the pull request
              github.issues.addLabels({
                owner: payload.repository.owner.login,
                repo: payload.repository.name,
                issue_number: prNumber,
                labels: ['rework']
              });
            }
