name: PR Review


on:
  pull_request_review:
    types: [changes_requested]


jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add "reviewed" label
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo, number } = context.issue;
            const label = "reviewed";
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: number,
              labels: [label]
            });
