on:
  workflow_dispatch:

jobs:
  add_reviewed_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add reviewed label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');
            const { owner, repo } = context.repo;
            
            const addLabel = async (pull_request_number) => {
              const { data: reviews } = await github.pulls.listReviews({
                owner,
                repo,
                pull_number: pull_request_number
              });
              
              const changesRequested = reviews.some(review => review.state === 'CHANGES_REQUESTED');
              
              if (changesRequested) {
                await github.issues.addLabels({
                  owner,
                  repo,
                  issue_number: pull_request_number,
                  labels: ['reviewed']
                });
              }
            };
            
            const getOpenPullRequests = async () => {
              const { data: pullRequests } = await github.pulls.list({
                owner,
                repo,
                state: 'open'
              });
              
              for (const pullRequest of pullRequests) {
                await addLabel(pullRequest.number);
              }
            };
            
            getOpenPullRequests();
