name: Add Changes Requested Label

on:
  pull_request_review:
    types:
      - submitted

jobs:
  add_changes_requested_label:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if changes were requested by maintainer or collaborator
        id: check_changes_requested
        uses: actions/github/rest-api-calls@v3
        with:
          method: GET
          headers: |
            Authorization: ${{ secrets.GITHUB_TOKEN }}
          endpoint: repos/${{ github.repository }}/collaborators/${{ github.event.review.user.login }}

      - name: Set label based on review
        run: |
          if [ $? -eq 0 ]; then
            echo "Changes requested by maintainer or collaborator, adding label..."
            echo "::set-output name=label::changes requested"
          else
            echo "No changes requested by maintainer or collaborator, no action needed."
            echo "::set-output name=label::no_changes_requested"
          fi

      - name: Add label if changes requested
        if: steps.check_changes_requested.outputs.label == 'changes requested'
        uses: actions/github/rest-api-calls@v3
        with:
          method: POST
          headers: |
            Authorization: ${{ secrets.GITHUB_TOKEN }}
          endpoint: issues/${{ github.event.pull_request.number }}/labels
          body: |
            ["changes requested"]
