
on:
  pull_request_review:
    types:
      - submitted

jobs:
  add_reviewed_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add reviewed label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');
            const { owner, repo } = context.repo;
            const pull_request_number = context.payload.pull_request.number;
            const review_state = context.payload.review.state;
            const changes_requested = context.payload.review.state === 'changes_requested';
            
            const addLabel = async () => {
              if (changes_requested) {
                await github.issues.addLabels({
                  owner,
                  repo,
                  issue_number: pull_request_number,
                  labels: ['reviewed']
                });
              }
            };
            
            addLabel();
